"use client";

import { useMemo, useState } from 'react';
import { Award, Download, Gift, Scale, SlidersHorizontal, WalletCards } from 'lucide-react';
import { PageHeader } from '@/components/layout/PageHeader';
import { Card, CardBody } from '@/components/ui/Card';
import { StatRibbon } from '@/components/ui/StatRibbon';
import { DataRow, ProgressBar, SectionHeading, SegmentedControl, StatusPill } from '@/components/ui/ModulePrimitives';
import { compensationBands, employeeRewards, rewardSummary } from '@/data/rewards';

const money = (value: number, compact = false) => new Intl.NumberFormat('en-UG', { style: 'currency', currency: 'UGX', maximumFractionDigits: 0, notation: compact ? 'compact' : 'standard' }).format(value);

export default function TotalRewardsPage() {
  const [tab,setTab]=useState('Overview'); const [period,setPeriod]=useState('Annual');
  const total=useMemo(()=>Object.values(rewardSummary).reduce((sum,value)=>sum+value,0),[]);
  const multiplier=period==='Monthly'?1/12:1;
  return <><PageHeader title="Total Rewards" subtitle="Make the full value of compensation visible, fair, and easy to understand." icon={<Award size={28}/>} tabs={['Overview','Statements','Compensation bands']} activeTab={tab} onTabChange={setTab} actions={<button className="btn-primary" style={{background:'white',color:'var(--primary)'}}><Download size={16}/> Export summary</button>}/><main style={{padding:'0 24px 32px'}}>
    <StatRibbon stats={[{label:'Total reward spend',value:money(total,true),trend:'+6.2%',trendType:'neutral',icon:<WalletCards size={20}/>,color:'var(--primary)'},{label:'Base compensation',value:money(rewardSummary.base,true),description:'74.6% of total',icon:<Scale size={20}/>,color:'var(--success)'},{label:'Benefits value',value:money(rewardSummary.benefits,true),description:'12.1% of total',icon:<Gift size={20}/>,color:'var(--warning)'},{label:'Employees covered',value:124,description:'100% have statements',icon:<Award size={20}/>,color:'var(--text-4)'}]}/>
    {tab==='Overview'&&<div style={{display:'grid',gridTemplateColumns:'minmax(0,1.4fr) minmax(320px,.8fr)',gap:20,marginTop:20}}><Card><CardBody><SectionHeading title="Reward composition" description="Company-wide annual investment" action={<SegmentedControl options={['Annual','Monthly']} value={period} onChange={setPeriod}/>}/>{Object.entries(rewardSummary).map(([key,value],i)=>{const colors=['var(--primary)','var(--success)','var(--warning)','#6366f1'];return <div key={key} style={{marginBottom:21}}><div className="row-between mb-8"><span className="text-sm fw-700 text-2" style={{textTransform:'capitalize'}}>{key}</span><div><strong className="text-1">{money(value*multiplier,true)}</strong><span className="text-xs text-5" style={{marginLeft:8}}>{Math.round(value/total*100)}%</span></div></div><ProgressBar value={value/total*100} color={colors[i]} height={10}/></div>})}</CardBody></Card><Card><CardBody><SectionHeading title="Pay equity watch" description="Proactive signals across comparable roles"/><div style={{padding:18,borderRadius:12,background:'rgba(22,163,74,.08)',marginBottom:14}}><div className="row-between"><div><div className="text-xs fw-700 text-4 uppercase">Adjusted pay gap</div><strong style={{fontSize:28,color:'var(--success)'}}>1.8%</strong></div><StatusPill tone="success">Healthy</StatusPill></div><p className="text-xs text-4 mb-0">Within the company target of less than 3%.</p></div><DataRow title="3 employees below band" subtitle="Review recommended before next cycle" meta={<StatusPill tone="warning">Attention</StatusPill>}/><DataRow title="7 employees near band maximum" subtitle="Consider progression or promotion paths" meta={<StatusPill tone="primary">Plan</StatusPill>}/></CardBody></Card></div>}
    {tab==='Statements'&&<Card style={{marginTop:20}}><CardBody><SectionHeading title="Employee reward statements" description="A clear, shareable view of salary, incentives, benefits, and equity"/>{employeeRewards.map(e=>{const t=e.base+e.bonus+e.benefits+e.equity;return <DataRow key={e.name} leading={<div style={{width:40,height:40,borderRadius:'50%',display:'grid',placeItems:'center',background:'var(--primary-tint)',color:'var(--primary)',fontWeight:800}}>{e.name.split(' ').map(n=>n[0]).join('')}</div>} title={e.name} subtitle={e.role} meta={<div style={{minWidth:220,textAlign:'right'}}><strong className="text-1">{money(t)}</strong><div className="text-xs text-5">Total annual value</div></div>} onClick={()=>{}}/>})}</CardBody></Card>}
    {tab==='Compensation bands'&&<Card style={{marginTop:20}}><CardBody><SectionHeading title="Compensation bands" description="Market-aligned ranges with a live view of employee positioning" action={<button className="btn-neutral"><SlidersHorizontal size={15}/> Configure bands</button>}/>{compensationBands.map(b=><div key={b.role} style={{padding:'17px 0',borderBottom:'1px solid var(--border)',display:'grid',gridTemplateColumns:'minmax(220px,1fr) 2fr 100px',gap:24,alignItems:'center'}}><div><div className="text-sm fw-800 text-1 mb-4">{b.role}</div><div className="text-xs text-4">{b.department} · {b.people} people</div></div><div><div className="row-between text-xs text-5 mb-8"><span>{money(b.min,true)}</span><span>Mid {money(b.midpoint,true)}</span><span>{money(b.max,true)}</span></div><div style={{position:'relative'}}><ProgressBar value={b.position} height={9}/><div style={{position:'absolute',left:`${b.position}%`,top:-3,width:15,height:15,borderRadius:'50%',background:'white',border:'3px solid var(--primary)',transform:'translateX(-50%)'}}/></div></div><div style={{textAlign:'right'}}><strong className="text-1">{b.position}%</strong><div className="text-xs text-5">Avg position</div></div></div>)}</CardBody></Card>}
  </main></>;
}
