"use client";

import { useState } from 'react';
import { Check, CheckCircle2, Clock3, GitBranch, Plus, Settings2, Zap } from 'lucide-react';
import { PageHeader } from '@/components/layout/PageHeader';
import { Card, CardBody } from '@/components/ui/Card';
import { StatRibbon } from '@/components/ui/StatRibbon';
import { Modal } from '@/components/ui/Modal';
import { Input } from '@/components/ui/Input';
import { Select } from '@/components/ui/Select';
import { DataRow, SectionHeading, StatusPill } from '@/components/ui/ModulePrimitives';
import { approvals, workflows } from '@/data/workflows';

export default function WorkflowsPage() {
  const [tab, setTab] = useState('Workflows'); const [builder, setBuilder] = useState(false); const [handled, setHandled] = useState<number[]>([]);
  return <><PageHeader title="Workflows & Approvals" subtitle="Build consistent processes and keep every approval moving." icon={<GitBranch size={28}/>} tabs={['Workflows','My approvals','Activity']} activeTab={tab} onTabChange={setTab} actions={<button className="btn-primary" onClick={() => setBuilder(true)} style={{ background: 'white', color: 'var(--primary)' }}><Plus size={16}/> New workflow</button>}/><main style={{ padding: '0 24px 32px' }}>
    <StatRibbon stats={[{ label:'Active workflows', value:3, icon:<Zap size={20}/>, color:'var(--primary)' },{ label:'Pending approvals', value:approvals.length-handled.length, icon:<Clock3 size={20}/>, color:'var(--warning)' },{ label:'Completed this month', value:54, trend:'+12%', trendType:'positive', icon:<CheckCircle2 size={20}/>, color:'var(--success)' },{ label:'Median completion', value:'6.4h', description:'Across all workflows', icon:<Settings2 size={20}/>, color:'var(--text-4)' }]}/>
    {tab === 'Workflows' && <Card style={{ marginTop:20 }}><CardBody><SectionHeading title="Workflow library" description="Reusable approval logic across every people operation"/>{workflows.map(w => <DataRow key={w.id} leading={<div style={{ width:40,height:40,borderRadius:10,display:'grid',placeItems:'center',background:'var(--primary-tint)',color:'var(--primary)' }}><GitBranch size={17}/></div>} title={w.name} subtitle={`${w.category} · Starts when: ${w.trigger}`} meta={<div className="row gap-20 align-center" style={{ minWidth:310 }}><span className="text-xs text-4">{w.steps} steps</span><span className="text-xs text-4">{w.runs} runs</span><span className="text-xs fw-700 text-3" style={{ minWidth:80 }}>{w.owner}</span><StatusPill tone={w.status==='Active'?'success':'neutral'}>{w.status}</StatusPill></div>} onClick={() => setBuilder(true)}/>)}</CardBody></Card>}
    {tab === 'My approvals' && <Card style={{ marginTop:20 }}><CardBody><SectionHeading title="Waiting for you" description="Requests assigned to your approval step"/>{approvals.filter(a=>!handled.includes(a.id)).map(a => <DataRow key={a.id} leading={<div style={{ width:38,height:38,borderRadius:'50%',display:'grid',placeItems:'center',background:'var(--bg-page)',fontWeight:800,color:'var(--primary)' }}>{a.person.split(' ').map(n=>n[0]).join('')}</div>} title={a.request} subtitle={`${a.person} · ${a.workflow} · Waiting ${a.age}`} meta={<div className="row gap-8"><button className="btn-neutral">Review</button><button className="btn-primary" onClick={(e)=>{e.stopPropagation();setHandled([...handled,a.id]);}}><Check size={14}/> Approve</button></div>}/>) }{approvals.length===handled.length && <div style={{padding:50,textAlign:'center'}}><CheckCircle2 size={38} color="var(--success)"/><h3 className="text-lg fw-800 text-1">You’re all caught up</h3><p className="text-sm text-4">There are no approvals waiting for you.</p></div>}</CardBody></Card>}
    {tab === 'Activity' && <Card style={{marginTop:20}}><CardBody><SectionHeading title="Workflow activity" description="An audit-ready timeline of automated and human actions"/>{['Time-off request approved for Sarah Johnson','Equipment request routed to Finance','Policy exception submitted by Amina Nsubuga','Reminder sent to Daniel Okello'].map((x,i)=><DataRow key={x} leading={<CheckCircle2 size={18} color={i===1?'var(--primary)':'var(--success)'}/>} title={x} subtitle={['12 minutes ago · People Ops','48 minutes ago · Step 2 of 3','Yesterday · Awaiting manager','Yesterday · Automatic reminder'][i]}/>)}</CardBody></Card>}
  </main><Modal isOpen={builder} onClose={()=>setBuilder(false)} title="Create workflow" subtitle="Define a trigger first. Approval steps and conditions come next." width={620} footer={<><button className="btn-neutral" onClick={()=>setBuilder(false)}>Save draft</button><button className="btn-primary" onClick={()=>setBuilder(false)}>Build approval steps</button></>}><div className="col gap-16"><div><label className="text-sm fw-600 text-2 mb-8" style={{display:'block'}}>Workflow name</label><Input placeholder="e.g. Equipment purchase approval"/></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}><div><label className="text-sm fw-600 text-2 mb-8" style={{display:'block'}}>Category</label><Select><option value="people">People operations</option><option value="time">Time off</option><option value="finance">Finance</option><option value="it">IT &amp; equipment</option></Select></div><div><label className="text-sm fw-600 text-2 mb-8" style={{display:'block'}}>Trigger</label><Select><option value="submitted">Request is submitted</option><option value="changed">Employee field changes</option><option value="scheduled">On a schedule</option></Select></div></div><div style={{padding:18,border:'1px dashed var(--primary)',borderRadius:12,background:'var(--primary-tint)'}}><div className="text-sm fw-800 text-primary mb-4">Reusable by design</div><div className="text-xs text-4">Conditions, approvers, reminders, and escalation rules will be configured as independent steps.</div></div></div></Modal></>;
}
