"use client";

import { useState } from 'react';
import { BarChart3, Calendar, MessageSquareText, Plus, Send, Sparkles, Users } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { PageHeader } from '@/components/layout/PageHeader';
import { Card, CardBody } from '@/components/ui/Card';
import { StatRibbon } from '@/components/ui/StatRibbon';
import { Modal } from '@/components/ui/Modal';
import { Input } from '@/components/ui/Input';
import { Select } from '@/components/ui/Select';
import { DataRow, ProgressBar, SectionHeading, StatusPill } from '@/components/ui/ModulePrimitives';
import { departmentEngagement, engagementTrend, surveys } from '@/data/engagement';

export default function EngagementPage() {
  const [activeTab, setActiveTab] = useState('Overview');
  const [showCreate, setShowCreate] = useState(false);
  const tabs = ['Overview', 'Surveys', 'Insights'];
  return <>
    <PageHeader title="Employee Engagement" subtitle="Listen continuously, spot meaningful trends, and turn feedback into action." icon={<Sparkles size={28} />} tabs={tabs} activeTab={activeTab} onTabChange={setActiveTab} actions={<button className="btn-primary" onClick={() => setShowCreate(true)} style={{ background: 'white', color: 'var(--primary)' }}><Plus size={16} /> New survey</button>} />
    <main style={{ padding: '0 24px 32px' }}>
      <StatRibbon stats={[{ label: 'Engagement score', value: '79%', trend: '+3 pts', trendType: 'positive', icon: <Sparkles size={20} />, color: 'var(--primary)' }, { label: 'eNPS', value: '+42', trend: '+7', trendType: 'positive', icon: <BarChart3 size={20} />, color: 'var(--success)' }, { label: 'Response rate', value: '77%', description: '96 of 124 responses', icon: <Users size={20} />, color: 'var(--warning)' }, { label: 'Open comments', value: 18, description: '6 need follow-up', icon: <MessageSquareText size={20} />, color: 'var(--text-4)' }]} />
      {activeTab === 'Overview' && <div style={{ display: 'grid', gridTemplateColumns: 'minmax(0, 1.55fr) minmax(300px, .8fr)', gap: 20, marginTop: 20 }}>
        <Card><CardBody><SectionHeading title="Engagement trend" description="Rolling company score over the last six months" /><div style={{ height: 265 }}><ResponsiveContainer width="100%" height="100%"><AreaChart data={engagementTrend} margin={{ left: -22, right: 10 }}><defs><linearGradient id="engagementFill" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#A238FF" stopOpacity={.22}/><stop offset="95%" stopColor="#A238FF" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 3"/><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: 'var(--text-5)', fontSize: 12 }}/><YAxis domain={[50, 100]} axisLine={false} tickLine={false} tick={{ fill: 'var(--text-5)', fontSize: 12 }}/><Tooltip contentStyle={{ border: '1px solid var(--border)', borderRadius: 10, boxShadow: '0 8px 30px rgba(0,0,0,.08)' }}/><Area type="monotone" dataKey="score" stroke="#A238FF" strokeWidth={3} fill="url(#engagementFill)" /></AreaChart></ResponsiveContainer></div></CardBody></Card>
        <Card><CardBody><SectionHeading title="Current pulse" description="August Pulse Check" /><div style={{ padding: '12px 14px', borderRadius: 10, background: 'var(--primary-tint)', marginBottom: 18 }}><div className="row-between mb-8"><span className="text-sm fw-700 text-1">96 responses</span><span className="text-xs fw-700 text-primary">77%</span></div><ProgressBar value={77}/></div>{departmentEngagement.slice(0,3).map(d => <DataRow key={d.name} title={d.name} subtitle={`${d.responses} responses`} meta={<div style={{ textAlign: 'right' }}><div className="fw-800 text-1">{d.score}%</div><div className="text-xs" style={{ color: d.change >= 0 ? 'var(--success)' : 'var(--error)' }}>{d.change >= 0 ? '+' : ''}{d.change} pts</div></div>} />)}</CardBody></Card>
      </div>}
      {activeTab === 'Surveys' && <Card style={{ marginTop: 20 }}><CardBody><SectionHeading title="Survey library" description="Schedule, monitor, and reuse employee listening programs" />{surveys.map(s => <DataRow key={s.id} leading={<div style={{ width: 40, height: 40, display: 'grid', placeItems: 'center', borderRadius: 10, background: 'var(--primary-tint)', color: 'var(--primary)' }}><Send size={17}/></div>} title={s.title} subtitle={`${s.type} · ${s.audience} · Closes ${s.closes}`} meta={<div className="row gap-16 align-center" style={{ minWidth: 230 }}><div style={{ width: 110 }}><ProgressBar value={s.total ? s.responses / s.total * 100 : 0}/><span className="text-xs text-5">{s.responses}/{s.total}</span></div><StatusPill tone={s.status === 'Live' ? 'success' : s.status === 'Scheduled' ? 'primary' : 'neutral'}>{s.status}</StatusPill></div>} />)}</CardBody></Card>}
      {activeTab === 'Insights' && <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 20, marginTop: 20 }}>{departmentEngagement.map(d => <Card key={d.name}><CardBody><div className="row-between mb-16"><div><h3 className="text-base fw-800 text-1 m-0 mb-4">{d.name}</h3><span className="text-xs text-4">{d.responses} anonymous responses</span></div><strong style={{ fontSize: 26, color: 'var(--primary)' }}>{d.score}%</strong></div><ProgressBar value={d.score}/><p className="text-sm text-4 mb-0" style={{ marginTop: 14 }}>Belonging and manager support are the strongest drivers for this team.</p></CardBody></Card>)}</div>}
    </main>
    <Modal isOpen={showCreate} onClose={() => setShowCreate(false)} title="Create survey" subtitle="Start from a focused, reusable listening program." footer={<><button className="btn-neutral" onClick={() => setShowCreate(false)}>Cancel</button><button className="btn-primary" onClick={() => setShowCreate(false)}><Calendar size={15}/> Continue to questions</button></>}><div className="col gap-16"><div><label className="text-sm fw-600 text-2 mb-8" style={{display:'block'}}>Survey name</label><Input placeholder="e.g. September Pulse Check"/></div><div><label className="text-sm fw-600 text-2 mb-8" style={{display:'block'}}>Survey type</label><Select><option value="pulse">Pulse survey</option><option value="enps">eNPS</option><option value="lifecycle">Lifecycle survey</option></Select></div><div><label className="text-sm fw-600 text-2 mb-8" style={{display:'block'}}>Audience</label><Select><option value="all">All employees</option><option value="department">Selected departments</option><option value="location">Selected locations</option></Select></div></div></Modal>
  </>;
}
