"use client";
import { createContext, useContext, useEffect, useState } from 'react';
import type { ReactNode } from 'react';

export type LeaveType = 'Vacation' | 'Sick Leave' | 'Floating Holiday';
export type LeaveStatus = 'Pending Manager' | 'Pending HR' | 'Approved' | 'Denied' | 'Cancelled';
export type LeaveRequest = { id:string; employeeId:string; employeeName:string; type:LeaveType; startDate:string; endDate:string; hours:number; reason:string; status:LeaveStatus; submittedAt:string; managerNote?:string; hrNote?:string; decidedBy?:string; };
type Balance = Record<LeaveType,{available:number;used:number}>;
type NewLeave = Pick<LeaveRequest,'employeeId'|'employeeName'|'type'|'startDate'|'endDate'|'hours'|'reason'>;
type OperationsContextValue={requests:LeaveRequest[];balances:Record<string,Balance>;createLeave:(request:NewLeave)=>{ok:boolean;message:string};updateLeave:(id:string,updates:Partial<Pick<LeaveRequest,'type'|'startDate'|'endDate'|'hours'|'reason'>>)=>void;cancelLeave:(id:string)=>void;managerDecision:(id:string,approved:boolean,note:string,actor:string)=>void;hrDecision:(id:string,approved:boolean,note:string,actor:string)=>void;deleteLeave:(id:string)=>void;};
const defaultBalance=():Balance=>({'Vacation':{available:120,used:32},'Sick Leave':{available:64,used:8},'Floating Holiday':{available:16,used:0}});
const seed:LeaveRequest[]=[{id:'leave-1',employeeId:'4',employeeName:'David Kimani',type:'Sick Leave',startDate:'2026-09-03',endDate:'2026-09-03',hours:8,reason:'Medical appointment and recovery.',status:'Pending Manager',submittedAt:'2026-09-01T08:30:00Z'},{id:'leave-2',employeeId:'4',employeeName:'David Kimani',type:'Vacation',startDate:'2026-09-14',endDate:'2026-09-18',hours:40,reason:'Annual family holiday.',status:'Pending HR',submittedAt:'2026-08-30T10:00:00Z',managerNote:'Coverage confirmed with the sales team.'},{id:'leave-3',employeeId:'2',employeeName:'James Mwangi',type:'Vacation',startDate:'2026-07-01',endDate:'2026-07-03',hours:24,reason:'Annual leave.',status:'Approved',submittedAt:'2026-06-12T09:00:00Z',managerNote:'Approved.',hrNote:'Balance verified.',decidedBy:'Sarah Johnson'}];
const OperationsContext=createContext<OperationsContextValue|undefined>(undefined);
export function OperationsProvider({children}:{children:ReactNode}){const[requests,setRequests]=useState<LeaveRequest[]>(seed);const[balances,setBalances]=useState<Record<string,Balance>>({'2':{'Vacation':{available:96,used:56},'Sick Leave':{available:64,used:8},'Floating Holiday':{available:16,used:0}},'4':defaultBalance()});const[ready,setReady]=useState(false);
 useEffect(()=>{try{const saved=localStorage.getItem('easyhr-operations-v2');if(saved){const data=JSON.parse(saved);setRequests(data.requests);setBalances(data.balances)}}finally{setReady(true)}},[]);
 useEffect(()=>{if(ready)localStorage.setItem('easyhr-operations-v2',JSON.stringify({requests,balances}))},[requests,balances,ready]);
 const ensureBalance=(id:string)=>balances[id]??defaultBalance();
 const createLeave=(r:NewLeave)=>{const balance=ensureBalance(r.employeeId)[r.type];if(!r.startDate||!r.endDate||!r.reason.trim()||r.hours<=0)return{ok:false,message:'Complete all required fields with valid hours.'};if(r.endDate<r.startDate)return{ok:false,message:'End date cannot be before start date.'};if(r.hours>balance.available)return{ok:false,message:`Only ${balance.available} hours are available for ${r.type}.`};setBalances(p=>p[r.employeeId]?p:{...p,[r.employeeId]:defaultBalance()});setRequests(p=>[{...r,id:`leave-${Date.now()}`,status:'Pending Manager',submittedAt:new Date().toISOString()},...p]);return{ok:true,message:'Request sent to your manager.'}};
 const updateLeave=(id:string,u:Partial<Pick<LeaveRequest,'type'|'startDate'|'endDate'|'hours'|'reason'>>)=>setRequests(p=>p.map(r=>r.id===id&&r.status==='Pending Manager'?{...r,...u}:r));
 const cancelLeave=(id:string)=>setRequests(p=>p.map(r=>r.id===id&&r.status.startsWith('Pending')?{...r,status:'Cancelled'}:r));
 const managerDecision=(id:string,approved:boolean,note:string,actor:string)=>setRequests(p=>p.map(r=>r.id===id&&r.status==='Pending Manager'?{...r,status:approved?'Pending HR':'Denied',managerNote:note,decidedBy:actor}:r));
 const hrDecision=(id:string,approved:boolean,note:string,actor:string)=>{const request=requests.find(r=>r.id===id);if(!request||request.status!=='Pending HR')return;if(approved){const b=ensureBalance(request.employeeId)[request.type];if(request.hours>b.available)return;setBalances(p=>{const employee=p[request.employeeId]??defaultBalance();return{...p,[request.employeeId]:{...employee,[request.type]:{available:employee[request.type].available-request.hours,used:employee[request.type].used+request.hours}}}})}setRequests(p=>p.map(r=>r.id===id?{...r,status:approved?'Approved':'Denied',hrNote:note,decidedBy:actor}:r))};
 const deleteLeave=(id:string)=>setRequests(p=>p.filter(r=>r.id!==id||r.status==='Approved'));
 return <OperationsContext.Provider value={{requests,balances,createLeave,updateLeave,cancelLeave,managerDecision,hrDecision,deleteLeave}}>{children}</OperationsContext.Provider>}
export function useOperations(){const value=useContext(OperationsContext);if(!value)throw new Error('useOperations must be used within OperationsProvider');return value}
